---
title: ""
output: html_document
---

# Graduate Student Applications

An *excellent* [guide to graduate school admissions](https://docs.google.com/document/u/2/d/e/2PACX-1vQcAcPKrThKidO-o4inKguECF81jpes1Cjbrs0Jn5aky5zEKXr8xtGBB9NkL5mV56lQTnKfykKhm1zT/pub) process for the UC Santa Barbara Interdepartmental Graduate Program in Marine Science, but with information applicable to other programs. 

The [Hidden Curriculum](https://lor.instructure.com/resources/4dbadf21d0a84ce8b826d97c6f857adb?shared) presented by UW Madison on how to be a successful graduate student and the barriers faced when transitioning into graduate school.

# Funding for Graduate Students

- [The Johns Hopkins List of Graduate Student Funding Opportunities](https://research.jhu.edu/rdt/funding-opportunities/graduate/)

- [The Johns Hopkins List of Underrepresented Minority and Low-income Graduate Student Funding Opportunities](https://research.jhu.edu/rdt/funding-opportunities/underrepresented/)

- [NSF Graduate Research Fellowship Program](https://www.nsfgrfp.org) 

- [NASA Graduate Student funding opportunities](https://science.nasa.gov/learn/learner-opportunities/#gradops)

- [ROSES-24 Amendment 61: Future Investigators in NASA Earth and Space Science and Technology (FINESST)](https://science.nasa.gov/researchers/solicitations/roses-2023/amendment-61-future-investigators-in-nasa-earth-and-space-science-and-technology-smds-graduate-student-research-proposals-final-text-released-proposals-due-february-6-2024/)

- [AGU Bridge Program](https://www.agu.org/bridge-program?utm_source=Sharing_Science_email_12.5.23&utm_medium=email&utm_campaign=bridge_program&mkt_tok=OTg3LUlHVC01NzIAAAGQeVSnh8-F0QxqD5k2uCw6J-PsBxav2j6IgJkSpQjvNDWTlI4VAa9t6y8aHQFkOoR5hFY3MbtoZp2wJz-HmQdsS4FELz48bw7wTh5MQDGAWQ)

- [AMS Graduate Fellowships](https://www.ametsoc.org/index.cfm/ams/information-for/students/ams-scholarships-and-fellowships/ams-graduate-fellowships/)

- [NOAA Dr. Nancy Foster Scholarship Program](https://fosterscholars.noaa.gov)

- [Ford Foundation Dissertation Fellowship](https://www.nationalacademies.org/our-work/ford-foundation-dissertation-fellowships)

- [Link Foundation Ocean Engineering & Instrumentation Fellowship](https://linkoe.org/program-guidelines/)

- [Sea Grant Knauss Fellowship (1 year policy fellowship in Washington, D.C.)](https://seagrant.noaa.gov/knauss-fellowship-program/)

- [American Association of University Women](https://www.aauw.org/resources/programs/fellowships-grants/)

# Career Opportunities for Graduate Students

- [Active recruitment efforts in Marine Sciences (compiled by LatinX)](https://docs.google.com/spreadsheets/d/14ySe_J3KMrTUrIvi843btc6SmKefWNuVbReTsabotqM/edit)

- [Available graduate positions in oceanography/marine science](https://docs.google.com/spreadsheets/d/1lNarus2zbsYkkQFCrWPS-U2L1Ey4hL2WuBnSp72L1P0/edit#gid=1076480778)

- [Ocean Carbon and Biogeochemistry job and postdoc list](https://www.us-ocb.org/science-support/jobs-and-postdocs/)

- [ECO magazine ocean career list](https://www.ecomagazine.com/news/opportunity/)

# Field Opportunities for Graduate Students

- [UNOLS Cruise Opportunity program mailing list](https://www.unols.org/form/contact-us-form)

- [UNOLS Chief Scientist Training Cruise Program](https://www.unols.org/nsf-unols-chief-scientist-training-cruise)

# Summer Courses for Graduate Students

- [NASA/UMaine Calibration & Validation for Ocean Color Remote Sensing summer workshop](https://misclab.umeoce.maine.edu/OceanOpticsClass2023/about/)

- [Cornell Satellite Remote Sensing summer course](http://oceanography.eas.cornell.edu/satellite/)

- [MBL Microbial Diversity](https://www.mbl.edu/education/advanced-research-training-courses/course-offerings/microbial-diversity)

- [Summer Courses at Friday Harbor Labs](https://fhl.uw.edu/courses/)

# Community and Support Networks

- [Black in Marine Science](https://www.blackinmarinescience.org)

- [Black in Geoscience](https://twitter.com/blkingeoscience?lang=en)

- [National Association of Black Geoscientists](https://www.americangeosciences.org/society/national-association-black-geoscientists)

- [BWEEMS (Black Women in Ecology, Evolution, and Marine Science)](https://www.bweems.org)

- [Society for Advancement of Chicanos/Hispanics & Native American in Science](https://www.sacnas.org)

- [LatinX in the Marine Sciences](https://twitter.com/i/flow/login?redirect_after_login=%2Fi%2Fflow%2Flogin)

- [GeoLatinas](https://geolatinas.org)

- [Asian Americans and Pacific Islanders in Geosciences](https://aapigeosci.org)

- [Association of Filipino Scientists in America](https://linktr.ee/afsa.official)

- [The International Association for Geoscience Diversity](https://theiagd.org)

- [American Indian Science and Engineering Society](https://www.aises.org)

- [500 Queer Scientists](https://500queerscientists.com)

- [500 Women Scientists](https://500womenscientists.org)

- [Society for Women in Marine Science](https://swmsmarinescience.com)

- [Earth Science Women's Network](https://eswnonline.org)

- [Mentoring Physical Oceanography Women to Increase Retention (MPOWIR)](https://mpowir.org)

