---
title: "Outreach"
---
----

**Our obligation was to be authentic to the scientific story and to tell it uncompromisingly** 

P. Kalanithi in _When Breath Becomes Air_

----

# <span style="color: #002A5E;">**Smithsonian Microbes**</span>

Dr. Carlson and I participated in an initiative led by [Dr. Alyson Santoro](https://labs.eemb.ucsb.edu/santoro/alyson/) and the Smithsonian to develop content for the [Smithsonian Ocean Portal](https://ocean.si.edu/ocean-life/microbes
). The motivation of the portal was to find new ways of communicate microbial ocean science to the public. Check out the short film by filmaker [Brendan Byrne](https://vimeo.com/brendansbyrne) that describes our work!

<br>

<iframe src="https://player.vimeo.com/video/333852210?title=0&byline=0&portrait=0" width="640" height="360" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>
<p><a href="https://vimeo.com/333852210">Marine Microbes Pt. I - Microbial World</a> from <a href="https://vimeo.com/brendansbyrne">Brendan Byrne</a> on <a href="https://vimeo.com">Vimeo</a>.</p>

<br>

----

# <span style="color: #002A5E;">**NAAMES**</span>

* It was awesome sailing with [Nicole Estaphan](https://www.ksbw.com/news-team/a0dbf6cc-afdb-4b7f-bb98-7f50aab6249a), a journalist for WCVB-TV ABC Boston who put together 4 great videos about NAAMES. Check them out below!

<br>

<iframe width="560" height="315" src="https://www.youtube.com/embed/Fp3bNkXzbLI" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/YKbHJHfChSw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/gUUoa9JgujE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/O5QAg8L_xNM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br>

* Dr. Carlson and I contributed to the NASA’s Earth Observatory Blogs during each cruise we participated on. Check them out [here](https://earthobservatory.nasa.gov/blogs/fromthefield/category/naames/)!

----

# <span style="color: #002A5E;">**ACIDD**</span>

 [Dr. Kelsey Bisson](https://scholar.google.com/citations?user=8FrNCE0AAAAJ&hl=en) led a project funded by the [National Academies Keck Futures Initiative](http://www.nasonline.org/programs/keck-futures-initiative/) that wove together the strengths of art and science. She put together a team of four artists, [Celia Jacobs](http://www.celiaj.com), [Dustin Hayes](http://lvl3official.com/walter-etc/), and [Gad Girling](https://gadgirling.myportfolio.com/projects), who worked to bring oceanography to the public eye through their mediums of art, music, photography, writing, and film. 
 
- See the magazine they produced [here](https://issuu.com/migrationsmag/docs/finalmigrationszinepages)!

- Watch the video they produced below, which was featured at the 2019 [Environmental Film Festival](https://dceff.org/film/aquatic-cathartic/) in Washington, D.C.!

<br>

<iframe src="https://player.vimeo.com/video/281882446" width="640" height="360" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>
<p><a href="https://vimeo.com/281882446">Aquatic Cathartic</a> from <a href="https://vimeo.com/projectacidd">Project ACIDD</a> on <a href="https://vimeo.com">Vimeo</a>.</p>


