---
title: ""
output: html_document
---

# Publications

**Baetge, N.**, Halsey, K.H., Graff, J.R., Ver Wey, B., Westberry, T.K., Appel, A.E., Bourdin, G., Begouen Demeaux, C., Boss, E., Behrenfeld, M.J. (2024) [Physiological and interspecific factors determine diel changes in phytoplankton bio-optical properties](https://doi.org/10.1002/lno.12493). *Limnology and Oceanography*, (69)2, 390-407.
\
\
Knowles, B., Bonachela, J.A., Cieslik, N., Della Penna, A., Diaz, B., **Baetge, N.**, Behrenfeld, M.J., Naumovitz, K., Boss, E., Graff, J.R., Halsey, K.H., Haramaty, L., Karp-Boss, L., Bidle, K.D. (2023) [Altered growth and death in dilution-based viral predation assays](https://doi.org/10.1371/journal.pone.0288114). *Plos one*, 18(7), e0288114.
\
\
**Baetge, N.**, Bolaños, L., Della Penna, A., Gaube, P., Liu, S., Opalk, K., Graff, J., Giovannoni, S., Behrenfeld, M., Carlson, C. (2022) [Bacterioplankton Response to Physical Stratification following Deep Convection](https://online.ucpress.edu/elementa/article/10/1/00078/190269). *Elementa: Science of the Anthropocene.* 10(1), 00078.
\
\
Comstock, J., Nelson, C., James, A., Wear, E., **Baetge, N.**, Juknavorian, A., Carlson, C. (2022) [Bacterioplankton communities reveal horizontal and vertical influence of an Island Mass Effect](https://sfamjournals.onlinelibrary.wiley.com/doi/full/10.1111/1462-2920.16092). *Environmental Microbiology.* 24(9), 4193-4208.
\
\
Lewis, S., Russel, L., Saliba, G., Quinn, P., Baters, T., Carlson, C., **Baetge, N.**, Aluwihare, L., Boss, E., Haetjens, N., Frossard, A., Bell, T., Behrenfeld, M. (2022) [Characterization of Sea Surface Microlayer and Marine Aerosol Organic Composition using STXM-NEXAFS Microscopy and FTIR Spectroscopy](https://pubs.acs.org/doi/10.1021/acsearthspacechem.2c00119).  *ACS Earth and Space Chemistry.* 6(7), 1899-1913.
\
\
Diaz, B., Knowles, B., Johns, C., Laber, C., Bondoc, K.G.V,  Harvey, E., Lowenstein, D., Fredricks, J., Haramaty, L., Natale, F., Graff, J., Haentjens, N., Westberry, T., **Baetge, N.**, Mojica, K., Gaube, P., Boss, E., Carlson, C., Behrenfeld, M., Van Mooy, B., Bidle, K. (2021) [Seasonal mixed layer dynamics shape phytoplankton physiology, viral infection, and accumulation in the North Atlantic](https://www.nature.com/articles/s41467-021-26836-1). *Nature Communications.* 12(1), 6634.
\
\
Wagner, S., Harvey, E., **Baetge, N.**, McNair, H., Arrington, E., Stubbins, A. (2021) [Investigating atmospheric inputs of dissolved black carbon to the Santa Barbara Channel during the Thomas Fire (California, USA)](https://doi.org/10.1029/2021JG006442). *Journal of Geophysical Research: Biogeosciences*. 126(8), e2021JG006442.
\
\
**Baetge, N.**, Behrenfeld, M., Fox, J., Halsey, K., Mojica, K., Novoa, A., Stephens, B., Carlson, C. (2021). [The Seasonal Flux and Fate of Dissolved Organic Carbon through the Food Web in the Westen North Atlantic.](https://www.frontiersin.org/articles/10.3389/fmicb.2021.669883/abstract). *Frontiers in Microbiology.* 12, 669883.
\
\
Bolaños, L., Choi, C.J., Worden, A., **Baetge, N.**, Carlson, C., Giovannoni, S. (2021) [Seasonality of the microbial community composition in the western North Atlantic.](https://doi.org/10.3389/fmars.2021.624164). *Frontiers in Marine Science*. 8, 624164.
\
\
Hendrickson, B., Brooks, S., Thornton, D., Moore, R., Crosbie, E., Ziemba, L., Carlson, C., **Baetge, N.**, Mirrielees, J., and Alsante, A. (2020) [Role of Sea Surface Microlayer Properties in Cloud Formation.](https://doi.org/10.3389/fmars.2020.596225). *Frontiers in Marine Science*. 7, 596225.
\
\
**Baetge, N.**, Graff, J. R., Behrenfeld, M. J., & Carlson, C. A. (2020) [Net Community Production, Dissolved Organic Carbon Accumulation, and Vertical Export in the Western North Atlantic](https://doi.org/10.3389/fmars.2020.00227). *Frontiers in Marine Science*. 7, 227.
\
\
Bisson, K. M., **Baetge, N.**, Kramer, S. J., Catlett, D., Girling, G., McNair, H., Arrington, E., Hayes, D., Jacobs, C., James, A., Closset, I., Fischer, A., Wagner, S., Reading, M., Comstock, J., Amiri, S., Harvey, E., Carlson, C. Gaube, P., Drushka, K., Valentine, D. (2020) [California Wildfire Burns Boundaries Between Science and Art](https://doi.org/10.5670/oceanog.2020.110). *Oceanography*. 33(1), 16-19.
\
\
Liu, S., Parsons, R., Opalk, K., **Baetge, N.**, Giovannoni, S., Bolaños, L. M., Kujawinski, E.B., Longnecker, K., Lu. Y, Halewood, E., Carlson, C. A. (2020) [Different carboxyl-rich alicyclic molecules proxy compounds select distinct bacterioplankton for oxidation of dissolved organic matter in the mesopelagic Sargasso Sea.](https://doi.org/10.1002/lno.11405). *Limnology and Oceanography*. 65(7), 1532-1553.
\
\
Liu, S., **Baetge, N.**, Comstock, J., Opalk, K., Parsons, R., Halewood, E., English, C., Giovannoni, S., Bolanos, L., Nelson, C., Vergin, K., Carlson, C. (2020) [Stable isotope probing identifies bacterioplankton lineages capable of utilizing dissolved organic matter across a range of bioavailability.](https://www.frontiersin.org/articles/10.3389/fmicb.2020.580397/abstract). *Frontiers in Microbiology.* 11, 2364.
\
\
Saliba, G., Chen, C., Lewis, S., Russell. L, Quinn, P., Bates, T., Bell, T., Lawler, M., Saltzman, E., Sanchez, K., Moore, R., Shook, M., Rivellini, L., Lee, A., **Baetge, N.**, Carlson, C., Behrenfeld, M. (2020) [Seasonal Differences and Variability of Concentrations, Chemical Composition, and Cloud Condensation Nuclei of Marine Aerosol over the North Atlantic.](https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/2020JD033145). *Journal of Geophysical Research: Atmospheres.* 125(19).
\
\
Saliba, G., Chen, C. L., Lewis, S., Russell, L. M., Rivellini, L. H., Lee, A. K., Quinn, P.K., Bates, T.S., Haëntjens, N., Boss, E.S., Karp-Boss, L., **Baetge, N.**, Carlson, C., Behrenfeld, M. (2019) [Factors driving the seasonal and hourly variability of sea-spray aerosol number in the North Atlantic.](https://doi.org/10.1073/pnas.1907574116). *Proceedings of the National Academy of Sciences*. 116(41), 20309-20314.
\
\
Behrenfeld, M. J., Moore, R. H., Hostetler, C. A., Graff, J., Gaube, P., Russell, L. M., Chen, G., Doney, S.C., Giovannoni, S., Liu, H.,  Proctor, C., Bolaños, **Baetge, N.**, Davie-Martin, C., Westberry, T.K., Bates, T.S., Bell, T.G., Bidle, K.D.,, Boss, E.S., Brooks, S.D., Cairns, B., Carlson, C., Halsey, K., Harvey, E.L., Hu, Chuanmin, Karp-Boss, L., Kleb, M., Menden-Deuer, S., Morison, F., Quinn, P.K., Scarino, A.J., Anderson, B., Chowdhary, J., Crosbie, E., Ferrare, R., Hair, J.W., Hu., Y., Janz, S., Redemann, J., Saltzman, E., Shook, M., Siegel, D.A., Wisthaler, A., Marting, M.Y., Ziemba, L. (2019) [The North Atlantic aerosol and marine ecosystem study (NAAMES): science motive and mission overview.](https://doi.org/10.3389/fmars.2019.00122). *Frontiers in Marine Science.* 6, 122.
