# Undergraduate Research

This is an informal guide for undergraduates who are interested in exploring science as a career option by getting involved and contributing in laboratory research. This guide was initially crafted by my friend and colleague [Dr. Dylan Catlett](https://scholar.google.com/citations?user=2OnvnAkAAAAJ&hl=en) and I will continue to adapt it over time. 

I encourage you to tap into your network and ask others, including your professors and TAs, for additional information and advice.

## Career trajectories

There are many career paths in (environmental) science, including in academia (i.e, universities, community colleges), government organizations, policy and law, and in the private sector. If you're interested in any of these careers, seeking out research experience as an undergraduate is a great way to expand your network and develop/hone skills that translate across all of these paths, including teamwork, critical thinking, writing and communication, and data generation, analysis and interpretation.

A graduate degree (MS, PhD) is not required to land a good job in science, but it can help broaden your options. Most high-quality graduate programs in scientific disciplines require minimal coursework relative to an undergraduate degree and focus on practical research experiences. Research experience is usually required to be admitted to graduate school. Most who pursue graduate degrees in scientific disciplines do not pay out of pocket for tuition and associated fees, and receive a living wage and benefits (health insurance) while in school. 

## Before you start

- Remember, being “prodigy”, “genius”, or having a 4.0 GPA is not a requirement for having a successful career in science or in research. 

-	Wherever you decide to start your career in science likely will not be where your career in science ends.

- You don't need to know much about research before you get involved! If you’re a 1st or 2nd year, you should have some evidence that you’re interested in science (for example, by taking some classes). If you’re a 3rd or 4th year, you should be close to declaring or declared as a science major and have taken a decent number of science classes.

- In general, everyone (you and your future research mentor) gets more out of undergraduate research when the undergraduate student sticks with it for a while. You should be pretty confident you want to give this a shot for 6 months or more (summer opportunities can be shorter term with a bigger time commitment per week). That said, if you find in the first couple of weeks that research just really isn't for you, don't force yourself through a bad time. Don't be afraid to approach the lab professor and communicate that you want to exit. It's ok! They should understand. After all, you were interested in exploring a research as a career option, not committing to it. 

- Undergraduates often start out in research with menial tasks like washing lab dishes, entering data into spreadsheets, etc. Expect to spend your first 1-3 months in research doing mostly boring stuff (but important! we wouldn't trust a meal that we know was prepared with dirty dishes or spoiled food). You never fully get off the hook from the boring stuff, but you tend to have to do less of it as you get more experience. If you enter the lab with some student research support or as part of an undergraduate research program, it's possible that you may 'fast track' to less menial lab activities. 

- There are paid and volunteer research opportunities available. The paid positions can be harder to come by, but there are likely programs at your university that you can look into. 

- Every research experience is different. Some dive into lab bench work, others focus on computational work, and some take to field work. There are labs that focus on basic research and others that focus on applied. Asking the people you’re interested in working with about the day-to-day is a good idea before you commit several months to an opportunity. 

- Whatever the kind of research, know that it is often slow for a number of reasons including that good work comes from careful work. You may find it boring after some initial excitement from learning lab methods, with more 'down time' as you become more experienced. But if you use the 'down time' to read the literature, make new questions, design new experiments, and explore the data available to you, you may find new excitement as the bigger picture to the lab's science becomes more clear. 

## Steps to get into a lab

### Prepare a curriculum vitae

- 1-page. It’s ok at your career stage if you don’t have much on there. Some things to include are your name and contact information, work and/or volunteer experiences from high school and/or college, your major and GPA, relevant coursework (this may change depending on who you’re giving it to), any other qualifications or skills. [OSU's Career Development Center](https://career.oregonstate.edu/careered/create-résumés-cvs-and-cover-letters) is a great resource for guidance.

### Identify programs, scholarships, research programs you're interested in

- Look through the faculty profiles on departmental webpages in the field(s) you’re interested in (e.g., [Microbiology](https://microbiology.oregonstate.edu) or [Botany and Plant Pathology](https://catalog.oregonstate.edu/college-departments/agricultural-sciences/botany-plant-pathology/)). Most faculty members have a lab website, so if the brief description on the directory page sounds interesting, check out their lab page for more information. If you don’t find a webpage on the departmental site, try google-ing.

- As you read through webpages, take note of the people working on the topics that sound the most interesting to you. Note their email addresses, if they have specific instructions for applying to work in the lab, and what general topic(s) they work on that are interesting to you.

- Many funding opportunities for undergraduate research require you to have a faculty sponsor, so when you talk with professors about working in their lab, it can help your case to say that you want to try for one of these.

#### OSU undergraduate research programs

[Undergraduate, Research, Scholarship and the Arts (URSA)](https://undergraduate.oregonstate.edu/research)

##### College of Science

- [Summer Undergraduate Research Experience (SURE)](https://science.oregonstate.edu/hands-on-experiences/undergraduate-research/sure-science-program)

- [Launching Undergraduate Research Experiences (LURE)](https://science.oregonstate.edu/hands-on-experiences/undergraduate-research/lure-science-program)

##### College of Agricultural Sciences

- [Beginning Researcher Support Program](https://agsci.oregonstate.edu/education/undergraduate-research/beginning-researcher-support-program)

- [Continuing Researcher Support Program](https://agsci.oregonstate.edu/education/undergraduate-research/continuing-researcher-support-program)

##### CEOS

- [Summer Research Internships](https://ceoas.oregonstate.edu/summer-research-internships-undergraduates)

- [NSF Research Experiences for Undergraduates (REU)](https://hmsc.oregonstate.edu/research-experiences-undergraduates)

#### External undergraduate support and opportunities

- [NASA undergraduate student funding opportunities](https://science.nasa.gov/learn/learner-opportunities/#undergrad)

- [Ford Foundation Predoctoral Fellowship](https://www.nationalacademies.org/our-work/ford-foundation-fellowships)

- [NOAA undergraduate funding opportunities](http://www.noaa.gov/opportunities/student-opportunities) 

- [Summer courses at Bermuda Institute of Ocean Sciences](https://www.us-ocb.org/science-support/student-opportunities/)

### Apply 

-	Most structured scholarship or other paid research training programs will have formal applications. Make sure to carefully read all the guidelines and follow them. If they include a description of what they are looking for in applicants, try to explicitly address those (it’s ok to use their wording) in your application.

-	Some labs will have formal guidelines listed on their webpage for applying to the lab. If so, follow the instructions carefully and make sure you send them everything they ask for. Writing something into your application/email/cover letter that shows you’ve read through their website and maybe one of their scientific papers (whether or not you understood any of it) is helpful.

- If you find a lab you’re interested in and they have no guidelines on how to apply/inquire about opportunities (this is extremely common…), it’s time to start cold-emailing…

### Cold-emailing

- Many undergraduate research positions are initiated after an undergraduate cold-emails a faculty member, grad student, or postdoc to say they want to try research. It can feel scary but you don't have to be scared!

- In your internet browsing above, you should try to identify 5-10 faculty whose research you’re interested in. Email all of them – there’s an example cold email below to guide you. 

- You should expect at least 50% of the faculty you email not to reply the first time. Give them 2-3 weeks and for those who don’t respond, it’s totally normal and acceptable to send a brief follow-up email to remind them (also an example below). 

- There’s a good chance ~50% won’t reply to the second email either. Don’t take this personally, it’s just how it is.

- Hopefully 1-3 faculty respond to your email, have an opening, and want to set up a meeting (sometimes they’ll call it an interview) to talk more with you. Respond promptly and professionally and make it as easy as possible for them to schedule a meeting with you (example below). 

- If you’re really interested in one lab group’s research but the professor isn’t responding to your cold emails, you can also try cold-emailing a graduate student or postdoc in their lab with the same sort of approach. Grad students and postdocs can be more responsive than their faculty advisors and are often the ones spending the most time in training/mentoring undergraduate researchers.

#### Here’s an example of a cold-email 20-year old Hannah Baetge (a current Marine Science and Conservation major at Duke), would write to 40-year old future Nick if he miraculously got a faculty job at Duke:

<font size="2"> 
Dear Dr. Baetge,

My name is Nick and I’m a 2rd year undergraduate student majoring in Marine Science and Conservation here at Duke. I’m writing to ask if you have any openings for undergraduates to join your lab as research assistants. I’ve been very interested in getting involved in marine microbiology research since taking MARSCI 201, The Future of the Ocean. I found your webpage through the NSOE website and really enjoyed learning about your research on coastal phytoplankton and bacteria. Although my interests are extremely broad, I found your research involving the use of lab experiments and satellite observations to study wildfire ash impacts on plankton particularly interesting and I would be especially excited to apply my background in biology to research focused on similar questions. 

If you have any opportunities for undergraduate assistants to help in your research, I would love to be considered. Please find my resume attached and let me know if there is anything else I can do to be considered for an undergraduate researcher position in your lab.

Thank you very much for your time and consideration,

Hannah Baetge
</font>  


#### Here’s an example of a follow-up to the cold-email Hannah would send if she didn’t hear back for a few weeks. She would reply to the initial email she sent so it was attached to this follow-up email:

<font size="2"> 
Dear Dr. Baetge,

I wanted to follow up to make sure you received my message from a few weeks ago (see below). I have re-attached my resume to this email just in case. Please let me know if you have any openings for undergraduate researchers to join your lab, and if so, if I can provide any further information to improve my chances of being considered.

Thank you,

Hannah
</font>


#### Let’s say Dr. Baetge responds:

<font size="2"> 
Hi Hannah,

I’m happy to hear you’re interested in my lab group’s research and sorry for my delayed response. I've just come back with my students from the field! Are you available to talk in more detail in the next few weeks?

Thanks,

Nick
</font>


#### Hannah would then respond:

<font size="2"> 
Dear Dr. Baetge,

Thank you very much for your response! I would love to talk more. Over the next few weeks I’m available (list some dates) at [list some times] (be as brief but as flexible as possible here). Please let me know if you can find a convenient time in those windows.

Thanks again and looking forward to talking with you,

Hannah
</font>

### The meeting/interview

-	Study for this. Do your best to read 1 or 2 of your prospective research advisor’s scientific papers (the ones that interest you most!!) and take notes and write down questions. 

- Be prepared with questions. Both about the science and about logistics. How much am I expected to work? What will work look like? Is there opportunity to be compensated for this work (or “are there any scholarships I can apply for to be compensated for this work”)? Is there opportunity to earn course credits? Do a senior thesis? 

-	Don’t be late. Show up to the meeting 5 minutes early if anything. 

-	You usually don’t need to dress up, but you probably don’t want to show up in a bathing suit or run over straight from a workout either. 

-	Be yourself. Be honest about what you’re interested in (including if you don’t know), and don’t try to act like you know what they’re talking about if you don’t (you will probably get busted; it’s better to just ask questions). Thank them for taking the time at the beginning and end of the meeting and if they give you an opportunity to follow-up, don’t miss it  :)











